### ISSUE TITLE
Doesn't work on Sublime Text 3

### ISSUE THREAD

**Issue by kangax** [joneshf/sublime-grasp#2]
I just tried Grasp on Sublime 3 (build 3059) and it doesn't seem to work. Ctrl + Shift + G brings up prompt but it doesn't find anything afterwards.

**Comment by joneshf** [comment]
OKay, between this one and #1 I'm clearly going to have to actually fix this. Sorry I've been lazy.

**Comment by kangax** [comment]
thanks! looking forward

**Comment by amycheng** [comment]
not working with Sublime Text 2 either. I tried doing a search like `'#response'` and I also tried typing `response` to look for the my `response`  variable. Here is the Sublime Text 2 Console Ouput:

```
raceback (most recent call last):
  File "./grasp.py", line 31, in run_grasp
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./grasp.py", line 31, in run_grasp
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
no command for selector: noop:
no command for selector: noop:
Traceback (most recent call last):
  File "./grasp.py", line 31, in run_grasp
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./grasp.py", line 31, in run_grasp
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by mrspeaker** [comment]
There were a couple of errors that were being silently eaten for me on this: first, the "grasp" command, although is in my bash path, wasn't being found. I changed:

```
command = ['grasp']
```

to:

```
 command = ['/usr/local/bin/grasp']
```

To fix that. Next, I was getting the dreaded "env: node: no such file or directory" error and had to do:

```
sudo ln -s /usr/local/bin/node /usr/bin/node 
```

Works in Sublime Text 3 for me now, though obviously my changes are not very generic!

**Comment by con-ssc** [comment]
In windows this error looks like "FileNotFoundError: [WinError 2]" although grasp is together with all other node stuff in the path.
